run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - typecheck

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - fmt.Fprintf
      - fmt.Printf

issues:
  exclude-dirs:
    - dist
    - docs
    - testdata
